// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProductService.proto

package com.product.grpc;

public interface ProductOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.product.grpc.Product)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 itemid = 1;</code>
   * @return The itemid.
   */
  int getItemid();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string category = 3;</code>
   * @return The category.
   */
  java.lang.String getCategory();
  /**
   * <code>string category = 3;</code>
   * @return The bytes for category.
   */
  com.google.protobuf.ByteString
      getCategoryBytes();

  /**
   * <code>float price = 4;</code>
   * @return The price.
   */
  float getPrice();
}
