// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProductService.proto

package com.product.grpc;

public interface ProductsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.product.grpc.Products)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.product.grpc.Product product = 1;</code>
   */
  java.util.List<com.product.grpc.Product> 
      getProductList();
  /**
   * <code>repeated .com.product.grpc.Product product = 1;</code>
   */
  com.product.grpc.Product getProduct(int index);
  /**
   * <code>repeated .com.product.grpc.Product product = 1;</code>
   */
  int getProductCount();
  /**
   * <code>repeated .com.product.grpc.Product product = 1;</code>
   */
  java.util.List<? extends com.product.grpc.ProductOrBuilder> 
      getProductOrBuilderList();
  /**
   * <code>repeated .com.product.grpc.Product product = 1;</code>
   */
  com.product.grpc.ProductOrBuilder getProductOrBuilder(
      int index);
}
