// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProductService.proto

package com.product.grpc;

public interface ProductIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.product.grpc.ProductId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 itemid = 1;</code>
   * @return The itemid.
   */
  int getItemid();
}
