// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProductService.proto

package com.product.grpc;

public final class ProductServiceOuterClass {
  private ProductServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_product_grpc_Product_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_product_grpc_Product_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_product_grpc_Products_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_product_grpc_Products_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_product_grpc_ProductId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_product_grpc_ProductId_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024ProductService.proto\022\020com.product.grpc" +
      "\032\033google/protobuf/empty.proto\"H\n\007Product" +
      "\022\016\n\006itemid\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\020\n\010catego" +
      "ry\030\003 \001(\t\022\r\n\005price\030\004 \001(\002\"6\n\010Products\022*\n\007p" +
      "roduct\030\001 \003(\0132\031.com.product.grpc.Product\"" +
      "\033\n\tProductId\022\016\n\006itemid\030\001 \001(\0052\260\002\n\016Product" +
      "Service\022D\n\016getAllProducts\022\026.google.proto" +
      "buf.Empty\032\032.com.product.grpc.Products\022D\n" +
      "\013saveProduct\022\031.com.product.grpc.Product\032" +
      "\032.com.product.grpc.Products\022F\n\rremovePro" +
      "duct\022\031.com.product.grpc.Product\032\032.com.pr" +
      "oduct.grpc.Products\022J\n\020getProductWithId\022" +
      "\033.com.product.grpc.ProductId\032\031.com.produ" +
      "ct.grpc.ProductB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_com_product_grpc_Product_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_product_grpc_Product_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_product_grpc_Product_descriptor,
        new java.lang.String[] { "Itemid", "Name", "Category", "Price", });
    internal_static_com_product_grpc_Products_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_product_grpc_Products_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_product_grpc_Products_descriptor,
        new java.lang.String[] { "Product", });
    internal_static_com_product_grpc_ProductId_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_product_grpc_ProductId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_product_grpc_ProductId_descriptor,
        new java.lang.String[] { "Itemid", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
